=== msqr/matte/matte/tags/0.9/src/magoffin/matt/ma2/biz/import.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xml:lang="EN" targetNamespace="http://msqr.us/xsd/matte"
	xmlns:m="http://msqr.us/xsd/matte" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:annotation>
		<xs:documentation> This is the XML Schema for the Matte application. </xs:documentation>
	</xs:annotation>
	
	<xs:element name="collection-import" type="m:collection-import-type"/>

	<xs:complexType name="collection-import-type">
		<xs:sequence>
			<xs:element name="album" type="m:album-import-type" minOccurs="0" maxOccurs="unbounded"
			/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="base-import-type" abstract="true">
		<xs:sequence>
			<xs:element name="comment" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="album-import-type">
		<xs:complexContent>
			<xs:extension base="m:base-import-type">
				<xs:sequence>
					<xs:element name="item" type="m:item-import-type" minOccurs="0"
						maxOccurs="unbounded"/>
					<xs:element name="album" type="m:album-import-type" minOccurs="0"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="sort" type="m:album-import-sort-type" use="optional" default="date"/>
				<xs:attribute name="album-date" type="xs:date" use="optional"/>
				<xs:attribute name="creation-date" type="xs:dateTime" use="optional"/>
				<xs:attribute name="modify-date" type="xs:dateTime" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name = "album-import-sort-type">
		<xs:restriction base = "xs:string">
			<xs:enumeration value="date">
				<xs:annotation><xs:documentation>Sort by date, ascending.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>			

	<xs:complexType name="item-import-type">
		<xs:complexContent>
			<xs:extension base="m:base-import-type">
				<xs:sequence>
					<xs:element name="keywords" type="xs:string" minOccurs="0"/>
					<xs:element name="meta" type="m:metadata-import-type" 
						minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="archive-path" type="xs:string" use="required"/>
				<xs:attribute name="rating" type="xs:float" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="metadata-import-type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== msqr/matte/matte/tags/0.9.1/src-test/magoffin/matt/ma2/biz/impl/import-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection-import xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://msqr.us/xsd/matte ../../../../../../src/magoffin/matt/ma2/biz/import.xsd"
	xmlns="http://msqr.us/xsd/matte">
	<album name="My Test Import With XML Album" sort="date">
		<comment>This is a test album, testing comments. here.</comment>
		<item archive-path="My Test Import With XML Album/bee-action.jpg" name="Bee Action" rating="5">
			<comment>See the bee, in action!</comment>
			<keywords>bee, test</keywords>
		</item>
		<item archive-path="My Test Import With XML Album/IMG_4215.jpg" name="Henrietta feeds her chicks">
			<comment>Henrietta back with some tasty worms or insects for 
				her hungry chicks.</comment>
			<meta name="FOO">bar</meta>
		</item>
	</album>
</collection-import>
